CREATE DATABASE IF NOT EXISTS sk_bank;
USE sk_bank;

CREATE TABLE IF NOT EXISTS admins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS managers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    mobile VARCHAR(20) UNIQUE NOT NULL,
    email VARCHAR(150) DEFAULT NULL,
    account_no VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    dob DATE DEFAULT NULL,
    photo LONGTEXT DEFAULT NULL,
    status ENUM('approved','pending') DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS employees (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    mobile VARCHAR(20) UNIQUE NOT NULL,
    email VARCHAR(150) DEFAULT NULL,
    account_no VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    pin VARCHAR(10) DEFAULT NULL,
    dob DATE DEFAULT NULL,
    photo LONGTEXT DEFAULT NULL,
    status ENUM('approved','pending') DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS customers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    mobile VARCHAR(20) UNIQUE NOT NULL,
    email VARCHAR(150) DEFAULT NULL,
    account_no VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    customer_id VARCHAR(50) UNIQUE NOT NULL,
    gender VARCHAR(20) DEFAULT NULL,
    dob DATE DEFAULT NULL,
    photo LONGTEXT DEFAULT NULL,
    balance DECIMAL(12,2) DEFAULT 0.00,
    manager_approval TINYINT(1) NOT NULL DEFAULT 0,
    employee_approval TINYINT(1) NOT NULL DEFAULT 0,
    status ENUM('approved','pending') DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transactions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    account_no VARCHAR(50) NOT NULL,
    type VARCHAR(50) NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    description VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Upgrade databases created by an earlier version of this project.
ALTER TABLE managers
    ADD COLUMN IF NOT EXISTS dob DATE DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS photo LONGTEXT DEFAULT NULL;

ALTER TABLE employees
    ADD COLUMN IF NOT EXISTS pin VARCHAR(10) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS dob DATE DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS photo LONGTEXT DEFAULT NULL;

ALTER TABLE customers
    ADD COLUMN IF NOT EXISTS customer_id VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS gender VARCHAR(20) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS dob DATE DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS photo LONGTEXT DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS manager_approval TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS employee_approval TINYINT(1) NOT NULL DEFAULT 0;

INSERT INTO admins (username, password) VALUES
('admin', '$2y$10$8J8Gz5n0M4tvz/2l6sL7sOhxVQY4jH6MZ1xkN7vG2f7nA0Qk8l1G');

-- Default admin password: admin123
-- For security, change this password after the first login.
